version: "3.0"
services:
  server:
    image: ubuntu:22.04
    container_name: server_container
    hostname: apache_website
    volumes:
      - ./www:/var/www/html
      #- ./config/apache/000-default.conf:/000-default.conf
      - ./setup_apache.sh:/setup_apache.sh
      - ./init.sql:/init.sql
      #- ./php_errors.log:/var/log/php_errors.log
      #- /var/www/html/username/static/uploads
      #- ./www/static/uploads:/var/www/html/username/static/uploads_temp
    working_dir: /var/www/html
    ports:
      - "3000:80"
      - "3306:3306"
    environment:
      DEBIAN_FRONTEND: noninteractive
    command: >
      /bin/bash -c "apt-get update && apt-get install -y dos2unix &&
      cp /setup_apache.sh /tmp/setup_apache.sh &&
      dos2unix /tmp/setup_apache.sh &&
      chmod +x /tmp/setup_apache.sh &&
      /tmp/setup_apache.sh"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: apache_website
      PMA_USER: default_user
      PMA_PASSWORD: default_password
      UPLOAD_LIMIT: 64M
    ports:
      - "8181:80"
    depends_on:
      - server