DROP TABLE IF EXISTS animal;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS booking;
CREATE TABLE animal (
    id CHAR(36) PRIMARY KEY DEFAULT UUID(),
    specie VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL DEFAULT '',
    age VARCHAR(50) NOT NULL,
    habitat VARCHAR(100),
    dimensions VARCHAR(100),
    lifespan VARCHAR(100),
    diet VARCHAR(100),
    description TEXT DEFAULT '',
    image VARCHAR(255) NOT NULL DEFAULT ''
);
CREATE TABLE user (
    id CHAR(36) PRIMARY KEY DEFAULT UUID(),
    name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    telephone VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM("Administrator", "User") NOT NULL DEFAULT "User"
);
CREATE TABLE booking (
    id CHAR(36) PRIMARY KEY DEFAULT UUID(),
    user_id CHAR(36) NOT NULL,
    date DATE NOT NULL,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(id)
);
INSERT INTO animal (specie, name, age, habitat, dimensions, lifespan, diet, description, image) VALUES
('Elefante', 'Dumbo', '45 anni', 'Savane e foreste africane', 'Fino a 4 metri di altezza e 6.000 kg', '60-70 anni', 'Erbivoro – foglie, frutti e cortecce', 'A differenza di molti altri animali, gli elefanti vivono in gruppi familiari guidati da una femmina anziana, la matriarca. Questi giganti gentili sono noti per la loro incredibile memoria e per il legame profondo che instaurano con i membri del branco. Comunicano tra loro attraverso suoni a bassa frequenza, vibrazioni nel terreno e il contatto fisico. Passano gran parte della giornata a cercare cibo e acqua, e sono fondamentali per l’ecosistema, poiché aprono sentieri e disperdono semi. Nonostante la loro mole, gli elefanti possono muoversi con sorprendente grazia e sensibilità.', './static/images/elephant.jpg'),
('Tigre', 'Strisce', '8 anni', 'Foreste tropicali e taiga', 'Fino a 3 metri di lunghezza, 200-300 kg', '10-15 anni', 'Carnivora – cervi, cinghiali, bufali', 'La tigre è un predatore solitario e furtivo che vive e caccia da sola nel cuore delle foreste. Contrariamente ad altri felini sociali, stabilisce e difende un proprio territorio marcandolo con odori e graffi sugli alberi. Si muove silenziosa attraverso la vegetazione, sfruttando il mimetismo offerto dalle sue strisce, e attacca con precisione fulminea. Le tigri sono anche eccellenti nuotatrici e spesso si rinfrescano nei corsi d’acqua. Fiere, misteriose e potenti, sono considerate simboli di forza e bellezza selvaggia.', './static/images/tiger.jpg'),
('Giraffa', 'Macchia', '12 anni', 'Savane africane', 'Fino a 5,5 metri di altezza, 800-1.200 kg', '20-25 anni', 'Foglie di acacia e arbusti', 'Le giraffe sono animali sociali che si muovono in piccoli gruppi o in branchi flessibili, spesso guidati da femmine adulte. Il loro lunghissimo collo non contiene più vertebre di quello umano, ma queste sono allungate e permettono loro di raggiungere le foglie più alte degli alberi. I maschi si sfidano in combattimenti rituali chiamati “necking”, dove si colpiscono con il collo per stabilire la dominanza. Malgrado l’apparenza placida, possono correre a oltre 50 km/h per sfuggire ai predatori. Con il loro sguardo curioso e la loro eleganza innata, le giraffe sono tra le creature più affascinanti della savana.', './static/images/giraffe.jpg'),
('Zebra', 'Righetta', '10 anni', 'Praterie africane', 'Circa 1,5 metri al garrese, 300 kg', '20-25 anni', 'Erbivora – erba e piante basse', 'Le zebre vivono in branchi compatti dove la cooperazione è essenziale per la sopravvivenza. Ogni zebra ha un disegno unico di strisce, che sembra aiutare a confondere i predatori e a rafforzare il legame con i membri del gruppo. Sono animali estremamente vigili, pronti a lanciare un grido d’allarme al minimo segnale di pericolo. Quando attaccate, corrono in gruppo, proteggendo i piccoli al centro del branco. Sebbene sembrino simili ai cavalli, le zebre sono più selvatiche e difficilmente addomesticabili. La loro resistenza e il loro spirito di gruppo sono le chiavi della loro sopravvivenza.', './static/images/zebra.jpg'),
('Coccodrillo', 'Scagliotto', '30 anni', 'Fiumi e paludi tropicali', 'Fino a 6 metri, 1.000 kg', '50-70 anni', 'Carnivoro – pesci, uccelli, mammiferi', 'Il coccodrillo è un rettile preistorico che vive principalmente in ambienti d’acqua dolce, come fiumi e paludi. Passa ore immobile, con solo gli occhi e le narici fuori dall’acqua, pronto a scattare con forza incredibile per catturare una preda. Sebbene solitario nella caccia, può convivere pacificamente con altri individui nella stessa area. Dopo l’accoppiamento, la femmina costruisce un nido e protegge le uova fino alla schiusa, mostrando un’insospettabile cura materna. Dotato di una potente mascella e di un metabolismo lento, può rimanere settimane senza mangiare. È un predatore paziente e perfettamente adattato all’ambiente acquatico.', './static/images/crocodile.jpg'),
('Gorilla', 'Berto', '20 anni', 'Foreste equatoriali africane', 'Fino a 1,8 metri, 160-200 kg', '35-40 anni', 'Frutta, foglie e radici', 'Il gorilla è un primate straordinariamente intelligente e sociale, che vive in gruppi familiari guidati da un maschio dominante, chiamato “silverback” per la striscia argentea sulla schiena. Nonostante la sua stazza imponente, il gorilla ha un’indole pacifica e trascorre le giornate nutrendosi, riposando e socializzando. Comunica attraverso vocalizzazioni, gesti e sguardi, mostrando una gamma emotiva sorprendente. Il gruppo è unito e protetto, con ruoli ben definiti e grande attenzione verso i cuccioli. Il gorilla incarna forza e gentilezza, ed è un simbolo vivente dell’equilibrio nella foresta tropicale.', './static/images/gorilla.jpg'),
('Pinguino', 'Pippo', '5 anni', 'Coste e ghiacci antartici', '60-90 cm, 15-40 kg', '15-20 anni', 'Pesce, calamari, krill', 'Il pinguino è un uccello acquatico che ha scambiato il volo per una straordinaria abilità nel nuoto. Vive in colonie numerose e rumorose, soprattutto nelle fredde regioni dell’Antartide. Durante la stagione riproduttiva, maschi e femmine si alternano nel proteggere le uova, affrontando temperature estreme e lunghi digiuni. I pinguini comunicano con richiami vocali unici per riconoscersi tra migliaia di individui. Hanno un comportamento curioso e cooperativo, e si muovono in gruppo sia sulla terra che in acqua. Dietro l’andatura buffa e i movimenti rigidi, si nasconde una straordinaria resistenza e determinazione.', './static/images/penguin.jpg'),
('Lama', 'Paco', '8 anni', 'Ande sudamericane', '1,7-1,8 metri, 130-200 kg', '15-20 anni', 'Erbivoro – erba e fieno', 'Il lama è un animale domestico originario delle Ande, da secoli utilizzato come animale da soma e compagno dell’uomo. Ha un’indole calma ma può diventare capriccioso se infastidito, spesso risolvendo le dispute con sputi e ringhi. Vive in piccoli gruppi sociali con una gerarchia ben definita. Dotato di piedi morbidi e adattati alla montagna, riesce a muoversi agilmente anche su terreni impervi. Ha un carattere curioso, osservatore e spesso affettuoso con chi gli è familiare. Il suo aspetto soffice e il muso espressivo lo rendono irresistibile agli occhi di molti.', './static/images/llama.jpg'),
('Ippopotamo', 'Tonno', '18 anni', 'Fiumi e laghi africani', 'Fino a 5 metri, 1.500-3.000 kg', '40-50 anni', 'Erbivoro – erbe acquatiche', 'L’ippopotamo trascorre gran parte della giornata immerso nell’acqua per rinfrescarsi e proteggere la pelle sensibile dal sole. Nonostante l’aspetto goffo e placido, è uno degli animali più pericolosi della savana, capace di muoversi rapidamente sia in acqua che sulla terra. Vive in gruppi composti da femmine e piccoli, dominati da un maschio territoriale. Quando non è in acqua, pascola silenziosamente di notte. Comunica attraverso suoni gravi che si propagano anche sott’acqua. L’ippopotamo è una presenza imponente, tra il mondo acquatico e quello terrestre, con una forza sorprendente e un comportamento imprevedibile.', './static/images/hippopotamus.jpg'),
('Panda', 'Bambù', '6 anni', 'Foreste montane cinesi', '1,5 metri, 100-150 kg', '20-25 anni', 'Quasi solo bambù', 'Il panda gigante è noto per la sua dieta quasi esclusivamente a base di bambù, che consuma per ore ogni giorno grazie a potenti mascelle e uno “pseudo-pollice” che gli permette di afferrare i fusti. Vive da solo nelle foreste montane della Cina, in territori ben definiti che marca con segnali odorosi. È un animale riservato e pacifico, che raramente si mostra aggressivo. Nonostante l’apparente pigrizia, può arrampicarsi sugli alberi e muoversi agilmente. Il suo aspetto tenero e il comportamento tranquillo lo hanno reso un simbolo universale di conservazione e armonia con la natura.', './static/images/panda.jpg'),
('Struzzo', 'Corridò', '7 anni', 'Savane e deserti africani', 'Fino a 2,7 metri, 150 kg', '40-45 anni', 'Semi, frutta, insetti', 'Lo struzzo è l’uccello più grande al mondo e, anche se non può volare, è uno dei più veloci corridori tra gli animali terrestri, capace di raggiungere i 70 km/h. Vive nelle savane e nei deserti, spesso in piccoli gruppi o associato a branchi di altri erbivori. Le sue potenti zampe non servono solo per correre, ma anche come arma difensiva contro i predatori. Ha un carattere curioso ma diffidente e usa l’altezza per sorvegliare l’ambiente circostante. Durante la stagione degli amori, i maschi eseguono spettacolari danze per attirare le femmine. Lo struzzo è un animale vigile e sorprendente, che unisce forza, eleganza e spirito libero.', './static/images/ostrich.jpg');
