name: Setup PHP
description: Setup PHP environment
inputs:
  php-version:
    required: true
  extensions:
    required: false
  tools:
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt update
        sudo apt install php${{ inputs.php-version }} -y
        sudo apt install php-${{ inputs.extensions }} -y
        if [ "${{ inputs.tools }}" = "composer" ]; then
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
        fi
      shell: bash
