name: Upload Artifact
description: Upload an artifact
inputs:
  name:
    required: true
  path:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p artifacts
        cp ${{ inputs.path }} artifacts/${{ inputs.name }}
      shell: bash
