name: PHP Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build PHP App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: TecWEBBoyz/actions/checkout

      - name: Setup PHP
        uses: TecWEBBoyz/actions/setup-php
        with:
          php-version: '8.1' # Specifica la versione di PHP necessaria
          extensions: mbstring, intl, pdo, pdo_mysql
          tools: composer

      - name: Install dependencies
        run: |
          cd www
          composer install --no-dev --optimize-autoloader

      - name: Prepare artifact
        run: |
          mkdir release
          cp -R www release/
          tar -czvf php-app.tar.gz -C release .

      - name: Upload artifact
        uses: TecWEBBoyz/actions/upload-artifact
        with:
          name: php-app
          path: php-app.tar.gz

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: TecWEBBoyz/actions/download-artifact
        with:
          name: php-app
          path: ./

      - name: Create release
        uses: TecWEBBoyz/actions/release-action
        with:
          artifacts: php-app.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This is an automated release for version ${{ github.ref_name }}.
            
            Changelog:
            - Placeholder for release notes.